=== wkrupchenko/swe2/shop/src/test/resources/datasets/db.dtd
<!ELEMENT dataset (
    ADRESSE*,
    ARTIKELGRUPPE*,
    ARTIKEL*,
    KUNDE*,
    BESTELLUNG*,
    BESTELLPOSITION*,
    LIEFERUNG*,
    BESTELLUNG_LIEFERUNG*)>

<!ELEMENT ADRESSE EMPTY>
<!ATTLIST ADRESSE
    A_ID CDATA #REQUIRED
    A_PLZ CDATA #REQUIRED
    A_ORT CDATA #REQUIRED
    A_STRASSE CDATA #IMPLIED
    A_HAUSNR CDATA #IMPLIED
    A_ERZEUGT CDATA #REQUIRED
    A_AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT ARTIKELGRUPPE EMPTY>
<!ATTLIST ARTIKELGRUPPE
    AG_ID CDATA #REQUIRED
    AG_NAME CDATA #REQUIRED
>

<!ELEMENT ARTIKEL EMPTY>
<!ATTLIST ARTIKEL
    A_ID CDATA #REQUIRED
    A_BEZEICHNUNG CDATA #REQUIRED
    A_PREIS CDATA #REQUIRED
    A_ERHAELTLICH CDATA #IMPLIED
    A_ERZEUGT CDATA #REQUIRED
    A_AKTUALISIERT CDATA #REQUIRED
    A_ARTIKELGRUPPE_FK CDATA #REQUIRED
    A_IDX CDATA #REQUIRED
>

<!ELEMENT KUNDE EMPTY>
<!ATTLIST KUNDE
    K_ID CDATA #REQUIRED
    K_NACHNAME CDATA #REQUIRED
    K_VORNAME CDATA #REQUIRED
    K_SEIT CDATA #IMPLIED
    K_ART CDATA #IMPLIED
    K_FAMILIENSTAND CDATA #IMPLIED
    K_GESCHLECHT CDATA #IMPLIED
    K_RABATT CDATA #IMPLIED
    K_UMSATZ CDATA #IMPLIED
    K_EMAIL CDATA #REQUIRED
    K_NEWSLETTER CDATA #IMPLIED
    K_PASSWORT CDATA #REQUIRED
    K_ERZEUGT CDATA #REQUIRED
    K_AKTUALISIERT CDATA #REQUIRED
    K_ADRESSE_FK CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG EMPTY>
<!ATTLIST BESTELLUNG
    B_ID CDATA #REQUIRED
    B_KUNDE_FK CDATA #IMPLIED
    B_IDX CDATA #REQUIRED
    B_ERZEUGT CDATA #REQUIRED
    B_AKTUALISIERT CDATA #REQUIRED
    B_OFFENABGESCHLOSSEN CDATA #REQUIRED
>

<!ELEMENT BESTELLPOSITION EMPTY>
<!ATTLIST BESTELLPOSITION
    BP_ID CDATA #REQUIRED
    BP_BESTELLUNG_FK CDATA #REQUIRED
    BP_ARTIKEL_FK CDATA #REQUIRED
    BP_ANZAHL CDATA #REQUIRED
    BP_IDX CDATA #REQUIRED
>

<!ELEMENT LIEFERUNG EMPTY>
<!ATTLIST LIEFERUNG
    L_ID CDATA #REQUIRED
    L_LIEFERNR CDATA #REQUIRED
    L_TRANSPORT_ART CDATA #IMPLIED
    L_INLANDODERAUSLAND CDATA #IMPLIED
    L_ERZEUGT CDATA #REQUIRED
    L_AKTUALISIERT CDATA #REQUIRED
>

<!ELEMENT BESTELLUNG_LIEFERUNG EMPTY>
<!ATTLIST BESTELLUNG_LIEFERUNG
    BL_BESTELLUNG_FK CDATA #REQUIRED
    BL_LIEFERUNG_FK CDATA #REQUIRED
>

=== wkrupchenko/swe2/shop/src/test/resources/datasets/db.xml
<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE dataset SYSTEM "db.dtd">
<dataset>
  <ADRESSE A_ID="200" A_PLZ="76332" A_ORT="Bad Herrenalb" A_STRASSE="Tammweg" A_HAUSNR="23" A_ERZEUGT="2008-03-03 00:00:00.0" A_AKTUALISIERT="2008-03-03 00:00:00.0"/>
  <ADRESSE A_ID="201" A_PLZ="76275" A_ORT="Ettlingen" A_STRASSE="Richard-Wagner-Straße" A_HAUSNR="3" A_ERZEUGT="2010-03-07 00:00:00.0" A_AKTUALISIERT="2010-03-07 00:00:00.0"/>
  <ADRESSE A_ID="202" A_PLZ="76133" A_ORT="Karlsruhe" A_STRASSE="Erzbergerstraße" A_HAUSNR="5" A_ERZEUGT="2010-03-09 00:00:00.0" A_AKTUALISIERT="2010-03-09 00:00:00.0"/>
  <ADRESSE A_ID="203" A_PLZ="76133" A_ORT="Karlsruhe" A_STRASSE="Moltkestraße" A_HAUSNR="23" A_ERZEUGT="2009-10-20 00:00:00.0" A_AKTUALISIERT="2009-10-20 00:00:00.0"/>
  <ADRESSE A_ID="204" A_PLZ="22222" A_ORT="Musterstadt" A_STRASSE="Musterstraße" A_HAUSNR="21" A_ERZEUGT="2011-11-10 00:00:00.0" A_AKTUALISIERT="2011-11-10 00:00:00.0"/>
  <ARTIKELGRUPPE AG_ID="400" AG_NAME="Wintermode"/>
  <ARTIKELGRUPPE AG_ID="401" AG_NAME="Sommermode"/>
  <ARTIKELGRUPPE AG_ID="402" AG_NAME="Herbstmode"/>
  <ARTIKELGRUPPE AG_ID="403" AG_NAME="Frühlingsmode"/>
  <ARTIKELGRUPPE AG_ID="404" AG_NAME="Herren"/>
  <ARTIKELGRUPPE AG_ID="405" AG_NAME="Damen"/>
  <ARTIKEL A_ID="500" A_BEZEICHNUNG="Schlauchschaal" A_PREIS="39.89" A_ERHAELTLICH="0" A_ERZEUGT="2007-01-01 00:00:00.0" A_AKTUALISIERT="2007-01-01 00:00:00.0" A_ARTIKELGRUPPE_FK="400" A_IDX="0"/>
  <ARTIKEL A_ID="501" A_BEZEICHNUNG="T-Shirt Helios" A_PREIS="59.99" A_ERHAELTLICH="1" A_ERZEUGT="2007-04-21 00:00:00.0" A_AKTUALISIERT="2007-04-21 00:00:00.0" A_ARTIKELGRUPPE_FK="401" A_IDX="0"/>
  <ARTIKEL A_ID="502" A_BEZEICHNUNG="Socken" A_PREIS="19.89" A_ERHAELTLICH="1" A_ERZEUGT="2008-01-02 00:00:00.0" A_AKTUALISIERT="2008-01-02 00:00:00.0" A_ARTIKELGRUPPE_FK="401" A_IDX="1"/>
  <ARTIKEL A_ID="503" A_BEZEICHNUNG="Chino rot" A_PREIS="69.69" A_ERHAELTLICH="0" A_ERZEUGT="2010-06-01 00:00:00.0" A_AKTUALISIERT="2010-06-01 00:00:00.0" A_ARTIKELGRUPPE_FK="404" A_IDX="0"/>
  <ARTIKEL A_ID="504" A_BEZEICHNUNG="Pollunder" A_PREIS="50.0" A_ERHAELTLICH="1" A_ERZEUGT="2011-06-08 00:00:00.0" A_AKTUALISIERT="2011-06-08 00:00:00.0" A_ARTIKELGRUPPE_FK="400" A_IDX="1"/>
  <KUNDE K_ID="100" K_NACHNAME="Mustermann" K_VORNAME="Max" K_SEIT="2009-04-28 00:00:00.0" K_ART="p" K_FAMILIENSTAND="0" K_GESCHLECHT="0" K_RABATT="0.1" K_UMSATZ="112.99" K_EMAIL="mm@web.de" K_NEWSLETTER="0" K_PASSWORT="pwd" K_ERZEUGT="2010-05-10 00:00:00.0" K_AKTUALISIERT="2009-05-10 00:00:00.0" K_ADRESSE_FK="200"/>
  <KUNDE K_ID="101" K_NACHNAME="Musterfrau" K_VORNAME="Eva" K_SEIT="2009-05-03 00:00:00.0" K_ART="p" K_FAMILIENSTAND="0" K_GESCHLECHT="1" K_RABATT="0.09" K_UMSATZ="49.99" K_EMAIL="me@web.de" K_NEWSLETTER="0" K_PASSWORT="evam" K_ERZEUGT="2009-05-04 00:00:00.0" K_AKTUALISIERT="2009-05-04 00:00:00.0" K_ADRESSE_FK="201"/>
  <KUNDE K_ID="102" K_NACHNAME="Herzog" K_VORNAME="Claudia" K_SEIT="2009-12-23 00:00:00.0" K_ART="p" K_FAMILIENSTAND="1" K_GESCHLECHT="1" K_RABATT="0.0" K_UMSATZ="10.79" K_EMAIL="clahe@gmx.de" K_NEWSLETTER="1" K_PASSWORT="ppp" K_ERZEUGT="2010-01-03 00:00:00.0" K_AKTUALISIERT="2010-01-03 00:00:00.0" K_ADRESSE_FK="202"/>
  <KUNDE K_ID="103" K_NACHNAME="Brenner" K_VORNAME="Rainer" K_SEIT="2010-07-09 00:00:00.0" K_ART="p" K_FAMILIENSTAND="0" K_GESCHLECHT="0" K_RABATT="0.2" K_UMSATZ="549.99" K_EMAIL="brenner@web.de" K_NEWSLETTER="0" K_PASSWORT="geheim" K_ERZEUGT="2010-08-04 00:00:00.0" K_AKTUALISIERT="2010-08-04 00:00:00.0" K_ADRESSE_FK="203"/>
  <KUNDE K_ID="104" K_NACHNAME="Göhit" K_VORNAME="Klaus" K_SEIT="2011-09-01 00:00:00.0" K_ART="p" K_FAMILIENSTAND="2" K_GESCHLECHT="0" K_RABATT="0.15" K_UMSATZ="249.99" K_EMAIL="klaus-gö@web.de" K_NEWSLETTER="1" K_PASSWORT="pass&quot;" K_ERZEUGT="2011-09-01 00:00:00.0" K_AKTUALISIERT="2011-09-01 00:00:00.0" K_ADRESSE_FK="204"/>
  <BESTELLUNG B_ID="300" B_KUNDE_FK="100" B_IDX="0" B_ERZEUGT="2011-05-20 00:00:00.0" B_AKTUALISIERT="2011-05-20 00:00:00.0" B_OFFENABGESCHLOSSEN="0"/>
  <BESTELLUNG B_ID="301" B_KUNDE_FK="101" B_IDX="0" B_ERZEUGT="2011-09-21 00:00:00.0" B_AKTUALISIERT="2011-09-21 00:00:00.0" B_OFFENABGESCHLOSSEN="1"/>
  <BESTELLUNG B_ID="302" B_KUNDE_FK="103" B_IDX="0" B_ERZEUGT="2011-12-20 00:00:00.0" B_AKTUALISIERT="2011-12-20 00:00:00.0" B_OFFENABGESCHLOSSEN="1"/>
  <BESTELLUNG B_ID="303" B_KUNDE_FK="100" B_IDX="1" B_ERZEUGT="2012-05-20 00:00:00.0" B_AKTUALISIERT="2012-05-20 00:00:00.0" B_OFFENABGESCHLOSSEN="0"/>
  <BESTELLUNG B_ID="304" B_KUNDE_FK="104" B_IDX="0" B_ERZEUGT="2012-06-13 00:00:00.0" B_AKTUALISIERT="2012-06-13 00:00:00.0" B_OFFENABGESCHLOSSEN="0"/>
  <BESTELLUNG B_ID="305" B_KUNDE_FK="104" B_IDX="1" B_ERZEUGT="2012-06-13 00:00:00.0" B_AKTUALISIERT="2012-06-13 00:00:00.0" B_OFFENABGESCHLOSSEN="0"/>
  <BESTELLPOSITION BP_ID="600" BP_BESTELLUNG_FK="301" BP_ARTIKEL_FK="501" BP_ANZAHL="2" BP_IDX="0"/>
  <BESTELLPOSITION BP_ID="601" BP_BESTELLUNG_FK="301" BP_ARTIKEL_FK="503" BP_ANZAHL="1" BP_IDX="1"/>
  <BESTELLPOSITION BP_ID="602" BP_BESTELLUNG_FK="302" BP_ARTIKEL_FK="501" BP_ANZAHL="3" BP_IDX="0"/>
  <BESTELLPOSITION BP_ID="603" BP_BESTELLUNG_FK="303" BP_ARTIKEL_FK="503" BP_ANZAHL="1" BP_IDX="0"/>
  <BESTELLPOSITION BP_ID="604" BP_BESTELLUNG_FK="303" BP_ARTIKEL_FK="503" BP_ANZAHL="1" BP_IDX="1"/>
  <BESTELLPOSITION BP_ID="605" BP_BESTELLUNG_FK="303" BP_ARTIKEL_FK="501" BP_ANZAHL="2" BP_IDX="2"/>
  <BESTELLPOSITION BP_ID="606" BP_BESTELLUNG_FK="304" BP_ARTIKEL_FK="502" BP_ANZAHL="4" BP_IDX="0"/>
  <BESTELLPOSITION BP_ID="607" BP_BESTELLUNG_FK="304" BP_ARTIKEL_FK="500" BP_ANZAHL="1" BP_IDX="1"/>
  <LIEFERUNG L_ID="700" L_LIEFERNR="500123-001" L_TRANSPORT_ART="Straße" L_INLANDODERAUSLAND="I" L_ERZEUGT="2010-02-22 00:00:00.0" L_AKTUALISIERT="2010-02-22 00:00:00.0"/>
  <LIEFERUNG L_ID="701" L_LIEFERNR="500123-002" L_TRANSPORT_ART="Straße" L_INLANDODERAUSLAND="I" L_ERZEUGT="2010-04-12 00:00:00.0" L_AKTUALISIERT="2010-04-12 00:00:00.0"/>
  <LIEFERUNG L_ID="702" L_LIEFERNR="500123-003" L_TRANSPORT_ART="Luft" L_INLANDODERAUSLAND="I" L_ERZEUGT="2010-09-10 00:00:00.0" L_AKTUALISIERT="2010-09-10 00:00:00.0"/>
  <LIEFERUNG L_ID="703" L_LIEFERNR="500123-004" L_TRANSPORT_ART="Meer" L_INLANDODERAUSLAND="A" L_ERZEUGT="2011-02-22 00:00:00.0" L_AKTUALISIERT="2011-02-22 00:00:00.0"/>
  <LIEFERUNG L_ID="704" L_LIEFERNR="500123-005" L_TRANSPORT_ART="Straße" L_INLANDODERAUSLAND="I" L_ERZEUGT="2012-02-21 00:00:00.0" L_AKTUALISIERT="2012-02-21 00:00:00.0"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="300" BL_LIEFERUNG_FK="703"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="301" BL_LIEFERUNG_FK="700"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="302" BL_LIEFERUNG_FK="704"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="303" BL_LIEFERUNG_FK="703"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="304" BL_LIEFERUNG_FK="701"/>
  <BESTELLUNG_LIEFERUNG BL_BESTELLUNG_FK="305" BL_LIEFERUNG_FK="701"/>
</dataset>
